### ISSUE TITLE
install olympe on ubuntu 16.04 with ROS kinetic

### ISSUE THREAD

**Issue by snakehaihai** [Parrot-Developers/olympe#12]
Hi
I have a lot of errors installing anafi on ubuntu 16.04 that preloaded with ROS kinetic. 

I got a lot of error while installing the  olympe requirement.txt
![image](https://user-images.githubusercontent.com/6070995/77287257-19eba780-6d10-11ea-8e02-27862657ec1d.png)

Even with existing 18.04, If i have ROS inside, I cant install it. 
![image](https://user-images.githubusercontent.com/6070995/77287354-51f2ea80-6d10-11ea-8c88-a76d8885f1da.png)

Is there any simple walk around that allow me to install it with ROS?

Regards
Shenghai Yuan

**Comment by ndessart** [comment]
Hi,

If you need any help installing Olympe with ROS you should rather ask for help on the [Olympe Parrot developer forum](https://forum.developer.parrot.com/c/anafi/olympe/23). I don't have any experience with ROS so I won't be able to help you personally for ROS specific issues but [some members of the community have successfully setup an OIympe/ROS environment](https://forum.developer.parrot.com/t/use-olympe-from-a-ros-program/10009/15). They might be able to help you if you still have some troubles.

Now from your two screenshots (by the way it's best to share error logs as text), it looks like you're having some network connectivity issues in (1) and the error in (2) seems to be related to a configuration error of your apt repos.

That being said, since this is not an Olympe bug report I'm closing this issue.
